
const qs=new URLSearchParams(location.search);let STATION=qs.get('station')||qs.get('slug')||localStorage.getItem('station_slug')||localStorage.getItem('STATION_SLUG')||'';if(STATION){localStorage.setItem('station_slug',STATION);localStorage.setItem('STATION_SLUG',STATION);}
let settings={},station=null,active=null,currentRole='guest',rouletteSelectedId=localStorage.getItem(`creator_roulette_${STATION||'current'}`)||'';
const $=s=>document.querySelector(s);const $$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=n=>Number(n||0).toLocaleString('ko-KR');
const norm=s=>String(s||'').trim();
function toWon(v){let s=String(v??'').replace(/,/g,'').trim();if(!s)return 0;let n=Number(s);if(!Number.isFinite(n))return 0;if(s.includes('.'))return Math.round(n*10000);if(n>0&&n<1000)return Math.round(n*10000);return Math.round(n)}
function fromWon(v){return String(Math.round(Number(v||0)))}
function apiPath(path){const u=new URL(path,location.origin);if(STATION&&!u.searchParams.get('station'))u.searchParams.set('station',STATION);return u.pathname+u.search}
async function api(path,opt={}){const headers={'Content-Type':'application/json',...(opt.headers||{})};let res;try{res=await fetch(apiPath(path),{credentials:'include',...opt,headers})}catch(err){err.status='NETWORK';err.endpoint=path;throw err}let data={};try{data=await res.json()}catch(e){}if(!res.ok){const err=new Error(data.error||res.statusText||'요청 실패');err.status=res.status;err.endpoint=path;err.payload=data;throw err}return data}
function authBody(){return {}}
function creatorLoginUrl(){const next=encodeURIComponent(location.pathname+location.search);return STATION?`/station_login.html?station=${encodeURIComponent(STATION)}&next=${next}`:`/station_login.html?next=${next}`}
function goStationLogin(){location.href=creatorLoginUrl()}
function showLoginGate(){$('#loginGate').style.display='flex'}function hideLoginGate(){$('#loginGate').style.display='none'}
function showSuccess(msg){const t=$('#toast');t.textContent='성공 ALERT · '+msg;t.classList.add('show');clearTimeout(showSuccess._t);showSuccess._t=setTimeout(()=>t.classList.remove('show'),1300)}
function closeError(){$('#errorBg').style.display='none'}
function showError(page,e){const code=e?.status||'UNKNOWN';const endpoint=e?.endpoint||'';const msg=e?.message||'처리 실패';$('#errorText').textContent=`페이지명: ${page}\n오류코드: ${code}\nAPI: ${endpoint}\n로그: ${msg}`;$('#errorBg').style.display='flex'}
function handleError(page,e){if((e.message||'').includes('권한')||(e.message||'').includes('비밀번호')){showLoginGate()}showError(page,e)}
function isLive(){return !!(active?.broadcastLiveData?.live||settings?.broadcast?.broadcastLiveData?.live)}
function sectionOn(k){return !!(settings?.overlaySections||{})[k]}function donationOn(){return sectionOn('account')||sectionOn('creators')||sectionOn('creatorDonations')}function allowanceOn(){return sectionOn('allowance')}
function badge(el,on){if(!el)return;el.className='badge '+(on?'on':'off');el.textContent=on?'ON':'OFF'}
function clearInput(id){const el=typeof id==='string'?$('#'+id):id;if(el)el.value=''}
function addAmount(id,won){const el=$('#'+id);el.value=String(toWon(el.value)+won)}
function addCount(id,n){const el=$('#'+id);const cur=Math.max(0,parseInt(el.value||'0',10)||0);el.value=String(cur+n)}
function clearCount(id){const el=$('#'+id);if(el)el.value='1'}
function setSourceCheck(groupId,value){$$(`#${groupId} input[type=\"checkbox\"]`).forEach(x=>x.checked=x.value===value)}
function selectedSource(groupId){const x=$(`#${groupId} input[type=\"checkbox\"]:checked`);return x?x.value:''}
function creators(){const arr=Array.isArray(settings?.creators)?settings.creators.map(norm).filter(Boolean):[];return arr.length?arr:['수동입력']}
function selectedCreators(boxId){return $$(`#${boxId} input[type="checkbox"]:checked`).map(x=>x.value).filter(Boolean)}
function setCreatorChecks(boxId,on){$$(`#${boxId} input[type="checkbox"]`).forEach(x=>x.checked=!!on)}
function renderCreatorChecks(boxId){const list=creators();$('#'+boxId).innerHTML=list.map((c,i)=>`<label class="checkitem"><input type="checkbox" value="${esc(c)}" ${i===0?'checked':''}>${esc(c)}</label>`).join('')}
function renderDonationCreatorRows(){const list=creators();const box=$('#donationCreatorRows');if(!box)return;box.innerHTML=list.map((c,i)=>`<div class="creator-amount-row"><label class="creator-amount-top"><input type="checkbox" class="donation-creator-check" value="${esc(c)}" ${i===0?'checked':''} onchange="updateDonationPreview()"><span>${esc(c)}</span></label><div class="creator-amount-grid"><input class="input donation-creator-amount" inputmode="decimal" placeholder="금액" oninput="updateDonationPreview()"><button class="btn mini gray" onclick="setOnlyDonationCreator(${i})">전액</button></div></div>`).join('');setOnlyDonationCreator(0,false);updateDonationPreview()}
function donationRows(){return $$('.creator-amount-row').map(row=>({row,creator:row.querySelector('.donation-creator-check')?.value||'',checked:!!row.querySelector('.donation-creator-check')?.checked,amount:toWon(row.querySelector('.donation-creator-amount')?.value||0)}))}
function collectDonationRows(){return donationRows().filter(r=>r.checked&&r.creator&&r.amount>0).map(r=>({creator:r.creator,amount:r.amount,memo:norm($('#donationMemo')?.value)}))}
function donationTopAmount(){return toWon($('#donationAmount')?.value)}
function donationSplitAmount(){return collectDonationRows().reduce((s,r)=>s+toWon(r.amount),0)}
function updateDonationPreview(){const top=donationTopAmount();const split=donationSplitAmount();const diff=top-split;const topEl=$('#donationTopTotal'),splitEl=$('#donationSplitTotal'),diffEl=$('#donationDiff'),box=$('#donationDiffBox');if(topEl)topEl.textContent=fmt(top)+'원';if(splitEl)splitEl.textContent=fmt(split)+'원';if(diffEl)diffEl.textContent=fmt(diff)+'원';if(box){box.classList.toggle('ok',diff===0);box.classList.toggle('warn',diff!==0)}}
function setOnlyDonationCreator(idx,doUpdate=true){const rows=$$('.creator-amount-row');rows.forEach((row,i)=>{row.querySelector('.donation-creator-check').checked=i===idx;row.querySelector('.donation-creator-amount').value=i===idx?fromWon(donationTopAmount()):''});if(doUpdate)updateDonationPreview()}
function applyDonationAmountToChecked(){const total=donationTopAmount();if(total<=0)return showError('후원입력',Object.assign(new Error('총 금액을 먼저 입력하세요.'),{status:'VALIDATION'}));let any=false;$$('.creator-amount-row').forEach(row=>{if(row.querySelector('.donation-creator-check')?.checked){row.querySelector('.donation-creator-amount').value=fromWon(total);any=true}});if(!any)showError('후원입력',Object.assign(new Error('크리에이터를 체크하세요.'),{status:'VALIDATION'}));updateDonationPreview()}
function distributeDonationAmount(){const total=donationTopAmount();const rows=$$('.creator-amount-row').filter(row=>row.querySelector('.donation-creator-check')?.checked);if(total<=0)return showError('후원입력',Object.assign(new Error('총 금액을 먼저 입력하세요.'),{status:'VALIDATION'}));if(!rows.length)return showError('후원입력',Object.assign(new Error('크리에이터를 체크하세요.'),{status:'VALIDATION'}));$$('.donation-creator-amount').forEach(e=>e.value='');let base=Math.floor(total/rows.length),rem=total-base*rows.length;rows.forEach(row=>{let a=base;if(rem>0){a++;rem--}row.querySelector('.donation-creator-amount').value=fromWon(a)});updateDonationPreview()}
function getRouletteRules(){const r=settings?.roulette||{},lists=Array.isArray(r.lists)?r.lists:[],rules=Array.isArray(r.autoRules)?r.autoRules:[];return rules.filter(x=>x&&x.enabled!==false&&Number(x.minAmount||0)>0).map(rule=>{const list=lists.find(l=>String(l.id)===String(rule.listId));return list?{...rule,listTitle:list.title||'룰렛'}:null}).filter(Boolean)}
function selectedRouletteRule(){const v=$('#donationProcess')?.value||'';if(!v.startsWith('roulette:'))return null;const id=v.split(':')[1]||'';return getRouletteRules().find(r=>String(r.id)===String(id))||null}
function donationProcessOptions(){const presets=Array.isArray(settings?.presets)?settings.presets:[];const presetHtml=presets.filter(p=>p&&p.enabled!==false).map(p=>{const title=esc(p.title||p.id||'프리셋'),plus=esc(p.plusName||'추가'),minus=esc(p.minusName||'제외');return `<optgroup label="${title}"><option value="${plus}">${plus} (${fmt(p.plusPrice||0)})</option><option value="${minus}">${minus} (${fmt(p.minusPrice||0)})</option></optgroup>`}).join('');const rouletteHtml=getRouletteRules().length?`<optgroup label="룰렛 자동">${getRouletteRules().map(r=>`<option value="roulette:${esc(r.id)}">룰렛 - ${esc(r.listTitle)} (${fmt(r.minAmount||0)}원/회)</option>`).join('')}</optgroup>`:'';return `<option value="후원">후원</option>${presetHtml}${rouletteHtml}`}
function presetOptions(){const arr=Array.isArray(settings?.presets)?settings.presets:[];const html=arr.filter(p=>p&&p.enabled!==false).map(p=>{const id=esc(p.id||p.title||'preset'),title=esc(p.title||p.id||'프리셋');const plus=esc(p.plusName||'추가'),minus=esc(p.minusName||'제외');return `<optgroup label="${title}"><option value="${id}:plus">${plus} (${fmt(p.plusPrice||0)})</option><option value="${id}:minus">${minus} (${fmt(p.minusPrice||0)})</option></optgroup>`}).join('');return html||'<option value="">프리셋 없음</option>'}
function fundingItems(){return Array.isArray(settings?.fundingData?.items)?settings.fundingData.items:[]}
function renderFundingSelect(){const items=fundingItems().filter(f=>f.enabled!==false);$('#fundingSelect').innerHTML=items.length?items.map(f=>`<option value="${esc(f.id)}">${esc(f.title||'펀딩')} (${fmt(f.current)}/${fmt(f.target)})</option>`).join(''):'<option value="">펀딩 없음</option>';renderFundingValues()}
function currentFunding(){const id=$('#fundingSelect')?.value||'';return fundingItems().find(f=>String(f.id)===String(id))}
function renderFundingValues(){const f=currentFunding();$('#fundingCurrent').value=f?fromWon(f.current):'';$('#fundingTarget').value=f?fromWon(f.target):''}
function setRouletteSelected(id){rouletteSelectedId=String(id||'');localStorage.setItem(`creator_roulette_${STATION||'current'}`,rouletteSelectedId);renderRouletteHistory()}
function selectedRouletteIds(){return rouletteSelectedId?[rouletteSelectedId]:[]}
function renderRoulette(){const r=settings?.roulette||{};const lists=Array.isArray(r.lists)?r.lists.filter(x=>x&&x.enabled!==false):[];const ids=lists.map(l=>String(l.id));if(!ids.includes(String(rouletteSelectedId))){rouletteSelectedId=String(r.current?.listId||ids[0]||'');if(rouletteSelectedId)localStorage.setItem(`creator_roulette_${STATION||'current'}`,rouletteSelectedId)}$('#rouletteChecks').innerHTML=lists.length?lists.map((l)=>`<label class="checkitem"><input type="radio" name="roulettePick" value="${esc(l.id)}" ${String(l.id)===String(rouletteSelectedId)?'checked':''} onchange="setRouletteSelected(this.value)">${esc(l.title||'룰렛')}</label>`).join(''):'<div class="empty">룰렛 없음</div>';const cur=r.current;$('#rouletteCurrent').textContent=cur?`현재 룰렛 : ${cur.listTitle||''} / 결과 ${cur.result||'-'} / 대기 ${(r.queue||[]).length}개`:'현재 룰렛 : 없음';renderRouletteHistory()}
function renderRouletteHistory(){const r=settings?.roulette||{};const ids=selectedRouletteIds();let hist=Array.isArray(r.history)?[...r.history].reverse():[];if(ids.length)hist=hist.filter(h=>ids.includes(String(h.listId)));$('#rouletteHistory').innerHTML=hist.length?hist.map((h,i)=>`<div class="history-row"><div class="num">${i+1}</div><div><b>${esc(h.result||'-')}</b><div class="muted">${esc(h.listTitle||'-')} · ${h.donor?esc(h.donor)+' · ':''}${h.createdAt?new Date(Number(h.createdAt)).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'}):''}</div></div></div>`).join(''):'<div class="empty">선택 룰렛 최근 결과 없음</div>'}
function renderNotice(){const ov=settings.overlaySections=settings.overlaySections||{};const on=!!ov.notice;const titleEl=$('#noticeTitle'),textEl=$('#noticeText');if(titleEl)titleEl.value=settings.noticeTitle||'공지';if(textEl)textEl.value=settings.notice||'';badge($('#noticeVisible'),on);const off=$('#noticeOff');if(off)off.style.display=on?'none':'block'}
function renderDisplay(){const ov=settings.overlaySections=settings.overlaySections||{};const list=[['account','계좌후원'],['creators','크리에이터'],['creatorDonations','크리에이터 후원'],['allowance','용돈'],['funding','펀딩'],['media','미디어'],['notice','공지'],['broadcastTimer','미션타이머']];$('#displayToggles').innerHTML=list.map(([k,t])=>`<button class="btn ${ov[k]?'green':'gray'}" data-display="${k}" onclick="toggleDisplayBtn(this)">${t} ${ov[k]?'ON':'OFF'}</button>`).join('')}
function toggleDisplayBtn(btn){const k=btn.dataset.display;settings.overlaySections=settings.overlaySections||{};settings.overlaySections[k]=!settings.overlaySections[k];renderDisplay();renderState()}
function renderState(){const onDonation=donationOn(),onFunding=sectionOn('funding'),onAllowance=allowanceOn(),onRoulette=(settings?.roulette?.enabled!==false);badge($('#donationVisible'),onDonation);badge($('#presetVisible'),onDonation);badge($('#fundingVisible'),onFunding);badge($('#rouletteVisible'),onRoulette);badge($('#noticeVisible'),sectionOn('notice'));$('#allowanceVisible').textContent=onAllowance?'용돈 ON':'용돈 OFF';$('#allowanceVisible').className='badge '+(onAllowance?'on':'off');$('#donationOff').style.display=onDonation?'none':'block';$('#presetOff').style.display=onDonation?'none':'block';$('#fundingOff').style.display=onFunding?'none':'block';const noticeOff=$('#noticeOff');if(noticeOff)noticeOff.style.display=sectionOn('notice')?'none':'block';$('#stAccount').textContent=sectionOn('account')?'ON':'OFF';$('#stCreators').textContent=sectionOn('creators')||sectionOn('creatorDonations')?'ON':'OFF';$('#stFunding').textContent=onFunding?'ON':'OFF';$('#stAllowance').textContent=`${fmt(settings?.allowanceData?.balance||0)}원`;$('#allowanceCurrent').textContent=`현재용돈 : ${fmt(settings?.allowanceData?.balance||0)}원`;badge($('#liveBadge'),isLive());$('#liveBadge').innerHTML=isLive()?'<span class="live-dot"></span>방송중':'입력잠김';['notice','mission','donation','preset','allowance','funding','roulette'].forEach(id=>{const btn=$(`.tab[data-tab="${id}"]`);let on=true;if(id==='notice')on=sectionOn('notice');if(id==='funding')on=onFunding;if(id==='mission')on=sectionOn('broadcastTimer');if(id==='allowance')on=onAllowance;if(id==='donation'||id==='preset')on=onDonation;if(id==='roulette')on=onRoulette;btn?.classList.toggle('off',!on)})}

function missionMs(){const t=settings?.broadcastTimerData||{};const now=Date.now();let elapsed=Math.max(0,Number(t.elapsedMs||0));if(t.running&&t.startedAt){const st=new Date(t.startedAt).getTime();if(st)elapsed+=Math.max(0,now-st)}if(t.mode==='until'&&t.targetAt){const target=new Date(t.targetAt).getTime();return Math.max(0,target-now)}if(t.mode==='countdown'){return Math.max(0,Number(t.durationMs||0)-elapsed)}return elapsed}
function formatHms(ms){let sec=Math.max(0,Math.floor(Number(ms||0)/1000));const h=String(Math.floor(sec/3600)).padStart(2,'0');sec%=3600;const m=String(Math.floor(sec/60)).padStart(2,'0');const s=String(sec%60).padStart(2,'0');return `${h}:${m}:${s}`}
function renderMissionModeHelp(){const mode=$('#missionMode')?.value||'countdown';const help=$('#missionHelp');if(!help)return;help.textContent=mode==='countdown'?'타임아웃: 입력한 분부터 카운트다운합니다.':mode==='until'?'맞춤시간: 지정한 시각까지 남은 시간을 표시합니다.':'진행시간: 0부터 경과 시간을 표시합니다.'}
function collectMissionBody(){return {label:norm($('#missionLabel')?.value),mode:$('#missionMode')?.value||'countdown',durationMin:$('#missionTimeoutMin')?.value||'',targetAt:$('#missionTargetAt')?.value||'',...authBody()}}
function setMissionDirty(on=true){missionDirty=!!on}
function renderMissionTimer(){const t=settings?.broadcastTimerData||{};if(!missionDirty){if($('#missionLabel'))$('#missionLabel').value=(Object.prototype.hasOwnProperty.call(t,'label')?String(t.label??''):'미션타이머');if($('#missionMode'))$('#missionMode').value=t.mode||'countdown';if($('#missionTimeoutMin'))$('#missionTimeoutMin').value=t.durationMs?String(Math.round(Number(t.durationMs||0)/60000)):'';if($('#missionTargetAt'))$('#missionTargetAt').value=t.targetAt?String(t.targetAt).slice(0,16):'';}if($('#missionCurrent')){const title=(Object.prototype.hasOwnProperty.call(t,'label')?String(t.label??''):'미션타이머');$('#missionCurrent').textContent=`${title?title+' : ':''}${formatHms(missionMs())} / ${t.running?'진행중':'멈춤'}`;}badge($('#missionVisible'),sectionOn('broadcastTimer'));renderMissionModeHelp()}
function startMissionClock(){clearInterval(startMissionClock._timer);startMissionClock._timer=setInterval(()=>{if($('#mission')?.classList.contains('active'))renderMissionTimer()},1000)}

function renderForms(){renderDonationCreatorRows();renderCreatorChecks('presetCreatorChecks');$('#donationProcess').innerHTML=donationProcessOptions();$('#presetProcess').innerHTML=presetOptions();renderFundingSelect();renderRoulette();renderDisplay();renderNotice();renderMissionTimer();renderState();updateDonationPreview()}

function applyRouletteData(roulette){
  if(!roulette) return;
  settings.roulette=roulette;
  renderRoulette();
}
async function refreshRouletteOnly(){
  try{
    const d=await api('/api/roulette');
    if(d.roulette) applyRouletteData(d.roulette);
  }catch(e){
    // 자동 갱신 실패는 버튼 조작을 막지 않도록 조용히 무시합니다.
  }
}
function rouletteExpireAt(run, roulette){
  if(!run||!run.startedAt) return 0;
  const duration=Number(run.duration||roulette.duration||3600);
  const hold=Math.max(3100, Number(roulette.resultHoldMs||0));
  const total=Math.max(0,Number(run.total||0));
  const sequence=Math.max(0,Number(run.sequence||0));
  const finalPageCount=total>5 && sequence>=total ? Math.ceil(total/5) : 1;
  return Number(run.startedAt||0)+duration+(hold*finalPageCount)+900;
}
let rouletteAdvanceLock='';
async function maybeAutoAdvanceRoulette(){
  const r=settings?.roulette||{};
  const cur=r.current;
  if(!cur||!cur.runId) return;
  const hasQueue=Array.isArray(r.queue)&&r.queue.length>0;
  if(!hasQueue) return;
  if(Date.now()<=rouletteExpireAt(cur,r)) return;
  if(rouletteAdvanceLock===cur.runId) return;
  rouletteAdvanceLock=cur.runId;
  try{
    const out=await api('/api/roulette/advance',{method:'POST',body:JSON.stringify({runId:cur.runId,...authBody()})});
    if(out.roulette) applyRouletteData(out.roulette);
  }catch(e){
    // 서버 자동 진행과 겹칠 수 있으니 조용히 재조회만 합니다.
    await refreshRouletteOnly();
  }finally{
    setTimeout(()=>{ if(rouletteAdvanceLock===cur.runId) rouletteAdvanceLock=''; },1200);
  }
}
function startRouletteAutoRefresh(){
  clearInterval(startRouletteAutoRefresh._timer);
  startRouletteAutoRefresh._timer=setInterval(()=>{
    const r=settings?.roulette||{};
    const rouletteTabActive=$('#roulette')?.classList.contains('active');
    const hasRunning=!!(r.current&&r.current.runId);
    const hasQueue=Array.isArray(r.queue)&&r.queue.length>0;
    if(hasRunning&&hasQueue) maybeAutoAdvanceRoulette();
    if(rouletteTabActive||hasRunning||hasQueue) refreshRouletteOnly();
  },800);
}
async function saveNotice(turnOn){try{settings.overlaySections=settings.overlaySections||{};if(turnOn)settings.overlaySections.notice=true;const body={noticeTitle:norm($('#noticeTitle').value)||'공지',notice:String($('#noticeText').value||''),overlaySections:settings.overlaySections,...authBody()};await api('/api/settings',{method:'POST',body:JSON.stringify(body)});showSuccess(turnOn?'공지 저장 + ON 완료':'공지 저장 완료');await loadAll(false)}catch(e){handleError('공지',e)}}
async function noticeOffAndSave(){try{settings.overlaySections=settings.overlaySections||{};settings.overlaySections.notice=false;await api('/api/settings',{method:'POST',body:JSON.stringify({overlaySections:settings.overlaySections,...authBody()})});showSuccess('공지 OFF 저장 완료');await loadAll(false)}catch(e){handleError('공지 OFF',e)}}
async function saveDisplay(){try{await api('/api/settings',{method:'POST',body:JSON.stringify({overlaySections:settings.overlaySections,...authBody()})});showSuccess('노출 저장 완료');await loadAll(false)}catch(e){handleError('노출',e)}}
async function saveDonation(){try{if(!isLive())throw new Error('방송시작 상태에서만 입력할 수 있습니다.');const donor=norm($('#donor').value);const amount=donationTopAmount();const source=selectedSource('donationSourceChecks');const rows=collectDonationRows();const selectedProcess=$('#donationProcess').value||'후원';const isRoulette=selectedProcess.startsWith('roulette:');const rr=isRoulette?selectedRouletteRule():null;if(!donor)throw new Error('도네이터명을 입력하세요.');if(amount<=0)throw new Error('총 금액을 입력하세요.');if(!source)throw new Error('계좌/투네 구분을 선택하세요.');if(!rows.length)throw new Error('크리에이터별 금액을 1개 이상 입력하세요.');const split=rows.reduce((s,r)=>s+toWon(r.amount),0);if(split!==amount)throw new Error(`총액과 크리에이터별 금액 합계가 다릅니다. 총액 ${fmt(amount)}원 / 분배 ${fmt(split)}원`);const body={donor,processType:isRoulette&&rr?`룰렛+${rr.listTitle}`:selectedProcess,accountTotal:source==='account'?amount:0,toonieTotal:source==='toonie'?amount:0,rows,rouletteRuleId:isRoulette?selectedProcess.replace('roulette:',''):'',...authBody()};await api('/api/donations/batch',{method:'POST',body:JSON.stringify(body)});['donor','donationAmount','donationMemo'].forEach(clearInput);$$('.donation-creator-amount').forEach(e=>e.value='');updateDonationPreview();showSuccess(`후원 저장 완료 ${rows.length}건`);await Promise.all([loadAll(false),loadRecent()])}catch(e){handleError('후원입력',e)}}
async function savePresetManual(){try{if(!isLive())throw new Error('방송시작 상태에서만 수동 입력할 수 있습니다.');const donor=norm($('#presetDonor').value);const count=Math.max(0,parseInt($('#presetCount').value||'0',10)||0);const selected=selectedCreators('presetCreatorChecks');const raw=$('#presetProcess').value||'';const [presetId,presetSide]=(raw.split(':'));const direction=$('#presetDirection').value||'plus';if(!raw)throw new Error('프리셋을 선택하세요.');if(!donor)throw new Error('도네이터명을 입력하세요.');if(count<=0)throw new Error('갯수를 입력하세요.');if(!selected.length)throw new Error('크리에이터를 선택하세요.');for(const creator of selected){const body={kind:'presetCount',donor,creator,presetId,presetSide,direction,count,...authBody()};await api('/api/manual-entry',{method:'POST',body:JSON.stringify(body)})}['presetDonor'].forEach(clearInput);$('#presetCount').value='1';showSuccess(`프리셋 ${direction==='minus'?'제외':'추가'} 완료 ${selected.length}건`);await Promise.all([loadAll(false),loadRecent()])}catch(e){handleError('프리셋 수동입력',e)}}
async function saveAllowance(){try{const body={amount:toWon($('#allowanceAmount').value),direction:$('#allowanceDirection').value,...authBody()};if(body.amount<=0)throw new Error('용돈 금액을 입력하세요.');await api('/api/allowance/adjust',{method:'POST',body:JSON.stringify(body)});clearInput('allowanceAmount');showSuccess('용돈 저장 완료');await loadAll(false)}catch(e){handleError('용돈 수동변경',e)}}

async function resetAllowance(){if(!confirm('현재 방송의 용돈을 0으로 초기화할까요?'))return;try{const d=await api('/api/allowance/reset',{method:'POST',body:JSON.stringify(authBody())});if(d.allowanceData)settings.allowanceData=d.allowanceData;showSuccess('용돈 0 초기화 완료');await loadAll(false)}catch(e){handleError('용돈 초기화',e)}}
async function resetPresetManual(){if(!confirm('현재 방송의 프리셋 수동보정 내역을 0으로 초기화할까요?'))return;try{await api('/api/preset-manual/reset',{method:'POST',body:JSON.stringify(authBody())});showSuccess('프리셋 수동보정 0 초기화 완료');await Promise.all([loadAll(false),loadRecent()])}catch(e){handleError('프리셋 초기화',e)}}
async function saveMissionTimerSettings(){try{const d=await api('/api/mission-timer/save',{method:'POST',body:JSON.stringify(collectMissionBody())});settings.broadcastTimerData=d.broadcastTimerData;missionDirty=false;showSuccess('미션타이머 설정 저장 완료');renderMissionTimer()}catch(e){handleError('미션타이머 설정저장',e)}}
async function startMissionTimer(resume){try{const body={...collectMissionBody(),resume:!!resume};const d=await api('/api/mission-timer/start',{method:'POST',body:JSON.stringify(body)});settings.broadcastTimerData=d.broadcastTimerData;missionDirty=false;settings.overlaySections=settings.overlaySections||{};settings.overlaySections.broadcastTimer=true;await api('/api/settings',{method:'POST',body:JSON.stringify({overlaySections:settings.overlaySections,...authBody()})});showSuccess(resume?'미션타이머 다시시작':'미션타이머 시작');await loadAll(false)}catch(e){handleError('미션타이머 시작',e)}}
async function pauseMissionTimer(){try{const d=await api('/api/mission-timer/pause',{method:'POST',body:JSON.stringify(authBody())});settings.broadcastTimerData=d.broadcastTimerData;missionDirty=false;showSuccess('미션타이머 멈춤');renderMissionTimer()}catch(e){handleError('미션타이머 멈춤',e)}}
async function endMissionTimer(){try{const d=await api('/api/mission-timer/end',{method:'POST',body:JSON.stringify(collectMissionBody())});settings.broadcastTimerData=d.broadcastTimerData;missionDirty=false;showSuccess('미션타이머 종료/초기화');await loadAll(false)}catch(e){handleError('미션타이머 종료',e)}}

async function saveFundingDirect(){try{const f=currentFunding();if(!f)throw new Error('펀딩을 선택하세요.');const data=JSON.parse(JSON.stringify(settings.fundingData||{items:[]}));const item=(data.items||[]).find(x=>String(x.id)===String(f.id));if(!item)throw new Error('펀딩을 찾을 수 없습니다.');item.current=Math.max(0,toWon($('#fundingCurrent').value));item.target=Math.max(0,toWon($('#fundingTarget').value));await api('/api/funding-data',{method:'POST',body:JSON.stringify({fundingData:data,...authBody()})});showSuccess('펀딩 금액 저장 완료');await loadAll(false)}catch(e){handleError('펀딩금액 변경',e)}}
async function saveFundingManual(){try{if(!isLive())throw new Error('방송시작 상태에서만 수동 입력할 수 있습니다.');const f=currentFunding();if(!f)throw new Error('펀딩을 선택하세요.');const donor=norm($('#fundDonor').value);const amount=toWon($('#fundAmount').value);if(!donor)throw new Error('도네이터명을 입력하세요.');if(amount<=0)throw new Error('금액을 입력하세요.');const body={kind:'funding',fundingId:f.id,donor,amount,sourceType:$('#fundSource').value,memo:'',...authBody()};await api('/api/manual-entry',{method:'POST',body:JSON.stringify(body)});['fundDonor','fundAmount'].forEach(clearInput);showSuccess('펀딩 추가 저장 완료');await Promise.all([loadAll(false),loadRecent()])}catch(e){handleError('펀딩 후원 추가',e)}}
async function startRoulette(){try{const ids=selectedRouletteIds();if(!ids.length)throw new Error('룰렛을 선택하세요.');setRouletteSelected(ids[0]);const body={listId:ids[0],count:$('#rouletteCount').value||1,duration:$('#rouletteDuration').value||undefined,...authBody()};const out=await api('/api/roulette/start',{method:'POST',body:JSON.stringify(body)});applyRouletteData(out.roulette);showSuccess('룰렛 시작');setTimeout(refreshRouletteOnly,250);setTimeout(refreshRouletteOnly,900)}catch(e){handleError('룰렛 시작',e)}}
async function resetRoulette(){try{const out=await api('/api/roulette/reset',{method:'POST',body:JSON.stringify(authBody())});applyRouletteData(out.roulette);showSuccess('룰렛 초기화')}catch(e){handleError('룰렛 초기화',e)}}
async function advanceRoulette(){try{const out=await api('/api/roulette/advance',{method:'POST',body:JSON.stringify(authBody())});applyRouletteData(out.roulette);showSuccess(out.run?'다음 룰렛 실행':'룰렛 종료');setTimeout(refreshRouletteOnly,250);setTimeout(refreshRouletteOnly,900)}catch(e){handleError('룰렛 다음',e)}}
async function loadRecent(){try{const d=await api('/api/manager/recent?limit=30');const arr=(d.donations||[]);$('#recentList').innerHTML=arr.length?arr.map((x,i)=>`<div class="recent"><div class="num">${i+1}</div><div><b>${esc(x.donor||'-')} → ${esc(x.creator||'-')}</b><div class="muted">${fmt(x.totalAmount||x.amount||0)}원 · ${esc(x.resultLabel||x.processType||'')}</div></div><button class="btn mini red" style="width:56px" onclick="deleteRecent('${esc(x.id)}')">삭제</button></div>`).join(''):'<div class="empty">최근 입력 없음</div>'}catch(e){$('#recentList').innerHTML=`<div class="muted danger-note">방송 로그인 후 최근 입력을 볼 수 있습니다.</div>`}}
async function deleteRecent(id){if(!confirm('이 입력을 삭제할까요?'))return;try{await api('/api/donations/'+encodeURIComponent(id),{method:'DELETE',body:JSON.stringify(authBody())});showSuccess('삭제 완료');await Promise.all([loadAll(false),loadRecent()])}catch(e){handleError('최근입력 삭제',e)}}
async function loadStationInfo(){const info=await api('/api/station-info');station=info.station||null;active=info.active||null;if(station?.slug&&!STATION){STATION=station.slug;localStorage.setItem('station_slug',STATION);localStorage.setItem('STATION_SLUG',STATION);rouletteSelectedId=localStorage.getItem(`creator_roulette_${STATION}`)||rouletteSelectedId||''}return info}
async function checkCreatorAuth(){const info=await api('/api/creator-auth');station=info.station||station;active=info.active||active;if(station?.slug){STATION=station.slug;localStorage.setItem('station_slug',STATION);localStorage.setItem('STATION_SLUG',STATION)}return info}
async function loadAll(showToast){let auth=null;try{auth=await checkCreatorAuth()}catch(e){currentRole='guest';if(e.status===401||e.status===403){$('#loginInfo').textContent=`${STATION||'방송국'} / 크리에이터 로그인 필요`;showLoginGate();return}throw e}settings=await api('/api/settings');currentRole=auth?.role||settings.role||'guest';settings.station=station;settings.broadcast=active;const roleText=currentRole==='master'?'최고관리자':currentRole==='station_admin'?'방송국관리자/크리에이터':currentRole==='broadcast_manager'?'방송매니저':'로그인 필요';$('#info').textContent=`${station?.name||STATION} / ${active?.title||'현재 방송'} / ${roleText} / ${isLive()?'방송중':'입력잠김'}`;$('#loginInfo').textContent=`${station?.name||STATION} / 현재 방송: ${active?.title||'없음'} / 크리에이터 로그인 필요`;if(!['master','station_admin'].includes(currentRole)){showLoginGate();return}hideLoginGate();renderForms();if(showToast)showSuccess('새로고침 완료')}
function switchTab(id){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===id));if(id==='roulette')refreshRouletteOnly()}
$('#tabs').addEventListener('click',e=>{const b=e.target.closest('.tab');if(b)switchTab(b.dataset.tab)});
function openOverlay(){const token=settings?.station?.overlayToken||station?.overlayToken||'';if(!token)return showError('오버레이',Object.assign(new Error('방송매니저 권한에서는 오버레이 토큰을 볼 수 없습니다.'),{status:'FORBIDDEN'}));window.open(`/overlay.html?station=${encodeURIComponent(STATION)}&token=${encodeURIComponent(token)}&monitor=1&v=${Date.now()}`,'_blank')}
function openSummary(){window.open(`/summary.html?station=${encodeURIComponent(STATION)}&v=${Date.now()}`,'_blank')}
function bindMissionInputs(){['missionLabel','missionMode','missionTimeoutMin','missionTargetAt'].forEach(id=>{const el=$('#'+id);if(el&&!el.dataset.boundMission){el.dataset.boundMission='1';el.addEventListener('input',()=>setMissionDirty(true));el.addEventListener('change',()=>{setMissionDirty(true);renderMissionModeHelp()});}})}
async function init(){try{await loadAll(false);bindMissionInputs();startRouletteAutoRefresh();startMissionClock();if(['master','station_admin'].includes(currentRole)){hideLoginGate();await loadRecent()}else{showLoginGate()}}catch(e){showError('초기 로딩',e);showLoginGate()}}
init();
