
const qs=new URLSearchParams(location.search);const STATION=qs.get('station')||qs.get('slug')||localStorage.getItem('station_slug')||'default';
let settings={},station=null,active=null,mobileAuth={broadcastId:'',password:''},rouletteSelectedId=localStorage.getItem(`creator_roulette_${STATION}`)||'';
const $=s=>document.querySelector(s);const $$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=n=>Number(n||0).toLocaleString('ko-KR');
const norm=s=>String(s||'').trim();
function toWon(v){let s=String(v??'').replace(/,/g,'').trim();if(!s)return 0;let n=Number(s);if(!Number.isFinite(n))return 0;if(s.includes('.'))return Math.round(n*10000);if(n>0&&n<1000)return Math.round(n*10000);return Math.round(n)}
function fromWon(v){return String(Math.round(Number(v||0)))}
function apiPath(path){const u=new URL(path,location.origin);if(!u.searchParams.get('station'))u.searchParams.set('station',STATION);return u.pathname+u.search}
async function api(path,opt={}){const headers={'Content-Type':'application/json',...(opt.headers||{})};let res;try{res=await fetch(apiPath(path),{credentials:'include',...opt,headers})}catch(err){err.status='NETWORK';err.endpoint=path;throw err}let data={};try{data=await res.json()}catch(e){}if(!res.ok){const err=new Error(data.error||res.statusText||'요청 실패');err.status=res.status;err.endpoint=path;err.payload=data;throw err}return data}
function authBody(){return mobileAuth?.broadcastId?{broadcastId:mobileAuth.broadcastId,broadcastPassword:mobileAuth.password,password:mobileAuth.password}:{}}
function getSavedBroadcastPassword(){return localStorage.getItem(`creator_pw_${STATION}_${active?.id||''}`)||''}
function saveBroadcastPassword(pw){if(active?.id)localStorage.setItem(`creator_pw_${STATION}_${active.id}`,pw)}
function clearSavedBroadcastPassword(){if(active?.id)localStorage.removeItem(`creator_pw_${STATION}_${active.id}`)}
function showLoginGate(){$('#loginGate').style.display='flex'}function hideLoginGate(){$('#loginGate').style.display='none'}
function showSuccess(msg){const t=$('#toast');t.textContent='성공 ALERT · '+msg;t.classList.add('show');clearTimeout(showSuccess._t);showSuccess._t=setTimeout(()=>t.classList.remove('show'),1300)}
function closeError(){$('#errorBg').style.display='none'}
function showError(page,e){const code=e?.status||'UNKNOWN';const endpoint=e?.endpoint||'';const msg=e?.message||'처리 실패';$('#errorText').textContent=`페이지명: ${page}\n오류코드: ${code}\nAPI: ${endpoint}\n로그: ${msg}`;$('#errorBg').style.display='flex'}
function handleError(page,e){if((e.message||'').includes('권한')||(e.message||'').includes('비밀번호')){clearSavedBroadcastPassword();mobileAuth={broadcastId:'',password:''};showLoginGate()}showError(page,e)}
function isLive(){return !!(active?.broadcastLiveData?.live||settings?.broadcast?.broadcastLiveData?.live)}
function sectionOn(k){return !!(settings?.overlaySections||{})[k]}function donationOn(){return sectionOn('account')||sectionOn('creators')||sectionOn('creatorDonations')}function allowanceOn(){return sectionOn('allowance')}
function badge(el,on){if(!el)return;el.className='badge '+(on?'on':'off');el.textContent=on?'ON':'OFF'}
function clearInput(id){const el=typeof id==='string'?$('#'+id):id;if(el)el.value=''}
function addAmount(id,won){const el=$('#'+id);el.value=String(toWon(el.value)+won)}
function addCount(id,n){const el=$('#'+id);const cur=Math.max(0,parseInt(el.value||'0',10)||0);el.value=String(cur+n)}
function clearCount(id){const el=$('#'+id);if(el)el.value='1'}
function setSourceCheck(groupId,value){$$(`#${groupId} input[type=\"checkbox\"]`).forEach(x=>x.checked=x.value===value)}
function selectedSource(groupId){const x=$(`#${groupId} input[type=\"checkbox\"]:checked`);return x?x.value:''}
function creators(){const arr=Array.isArray(settings?.creators)?settings.creators.map(norm).filter(Boolean):[];return arr.length?arr:['수동입력']}
function selectedCreators(boxId){return $$(`#${boxId} input[type="checkbox"]:checked`).map(x=>x.value).filter(Boolean)}
function setCreatorChecks(boxId,on){$$(`#${boxId} input[type="checkbox"]`).forEach(x=>x.checked=!!on)}
function renderCreatorChecks(boxId){const list=creators();$('#'+boxId).innerHTML=list.map((c,i)=>`<label class="checkitem"><input type="checkbox" value="${esc(c)}" ${i===0?'checked':''}>${esc(c)}</label>`).join('')}
function presetOptions(){const arr=Array.isArray(settings?.presets)?settings.presets:[];const html=arr.filter(p=>p&&p.enabled!==false).map(p=>{const id=esc(p.id||p.title||'preset'),title=esc(p.title||p.id||'프리셋');const plus=esc(p.plusName||'추가'),minus=esc(p.minusName||'제외');return `<optgroup label="${title}"><option value="${id}:plus">${plus} (${fmt(p.plusPrice||0)})</option><option value="${id}:minus">${minus} (${fmt(p.minusPrice||0)})</option></optgroup>`}).join('');return html||'<option value="">프리셋 없음</option>'}
function fundingItems(){return Array.isArray(settings?.fundingData?.items)?settings.fundingData.items:[]}
function renderFundingSelect(){const items=fundingItems().filter(f=>f.enabled!==false);$('#fundingSelect').innerHTML=items.length?items.map(f=>`<option value="${esc(f.id)}">${esc(f.title||'펀딩')} (${fmt(f.current)}/${fmt(f.target)})</option>`).join(''):'<option value="">펀딩 없음</option>';renderFundingValues()}
function currentFunding(){const id=$('#fundingSelect')?.value||'';return fundingItems().find(f=>String(f.id)===String(id))}
function renderFundingValues(){const f=currentFunding();$('#fundingCurrent').value=f?fromWon(f.current):'';$('#fundingTarget').value=f?fromWon(f.target):''}
function setRouletteSelected(id){rouletteSelectedId=String(id||'');localStorage.setItem(`creator_roulette_${STATION}`,rouletteSelectedId);renderRouletteHistory()}
function selectedRouletteIds(){return rouletteSelectedId?[rouletteSelectedId]:[]}
function renderRoulette(){const r=settings?.roulette||{};const lists=Array.isArray(r.lists)?r.lists.filter(x=>x&&x.enabled!==false):[];const ids=lists.map(l=>String(l.id));if(!ids.includes(String(rouletteSelectedId))){rouletteSelectedId=String(r.current?.listId||ids[0]||'');if(rouletteSelectedId)localStorage.setItem(`creator_roulette_${STATION}`,rouletteSelectedId)}$('#rouletteChecks').innerHTML=lists.length?lists.map((l)=>`<label class="checkitem"><input type="radio" name="roulettePick" value="${esc(l.id)}" ${String(l.id)===String(rouletteSelectedId)?'checked':''} onchange="setRouletteSelected(this.value)">${esc(l.title||'룰렛')}</label>`).join(''):'<div class="empty">룰렛 없음</div>';const cur=r.current;$('#rouletteCurrent').textContent=cur?`현재 룰렛 : ${cur.listTitle||''} / 결과 ${cur.result||'-'} / 대기 ${(r.queue||[]).length}개`:'현재 룰렛 : 없음';renderRouletteHistory()}
function renderRouletteHistory(){const r=settings?.roulette||{};const ids=selectedRouletteIds();let hist=Array.isArray(r.history)?[...r.history].reverse():[];if(ids.length)hist=hist.filter(h=>ids.includes(String(h.listId)));$('#rouletteHistory').innerHTML=hist.length?hist.map((h,i)=>`<div class="history-row"><div class="num">${i+1}</div><div><b>${esc(h.result||'-')}</b><div class="muted">${esc(h.listTitle||'-')} · ${h.donor?esc(h.donor)+' · ':''}${h.createdAt?new Date(Number(h.createdAt)).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'}):''}</div></div></div>`).join(''):'<div class="empty">선택 룰렛 최근 결과 없음</div>'}
function renderDisplay(){const ov=settings.overlaySections=settings.overlaySections||{};const list=[['account','계좌후원'],['creators','크리에이터'],['creatorDonations','크리에이터 후원'],['funding','펀딩'],['media','미디어'],['notice','공지']];$('#displayToggles').innerHTML=list.map(([k,t])=>`<button class="btn ${ov[k]?'green':'gray'}" data-display="${k}" onclick="toggleDisplayBtn(this)">${t} ${ov[k]?'ON':'OFF'}</button>`).join('')}
function toggleDisplayBtn(btn){const k=btn.dataset.display;settings.overlaySections=settings.overlaySections||{};settings.overlaySections[k]=!settings.overlaySections[k];renderDisplay();renderState()}
function renderState(){const onDonation=donationOn(),onFunding=sectionOn('funding'),onAllowance=allowanceOn(),onRoulette=(settings?.roulette?.enabled!==false);badge($('#donationVisible'),onDonation);badge($('#presetVisible'),onDonation);badge($('#fundingVisible'),onFunding);badge($('#rouletteVisible'),onRoulette);$('#allowanceVisible').textContent=onAllowance?'용돈 ON':'용돈 OFF';$('#allowanceVisible').className='badge '+(onAllowance?'on':'off');$('#donationOff').style.display=onDonation?'none':'block';$('#presetOff').style.display=onDonation?'none':'block';$('#fundingOff').style.display=onFunding?'none':'block';$('#stAccount').textContent=sectionOn('account')?'ON':'OFF';$('#stCreators').textContent=sectionOn('creators')||sectionOn('creatorDonations')?'ON':'OFF';$('#stFunding').textContent=onFunding?'ON':'OFF';$('#stAllowance').textContent=`${fmt(settings?.allowanceData?.balance||0)}원`;$('#allowanceCurrent').textContent=`현재용돈 : ${fmt(settings?.allowanceData?.balance||0)}원`;badge($('#liveBadge'),isLive());$('#liveBadge').innerHTML=isLive()?'<span class="live-dot"></span>방송중':'입력잠김';['donation','preset','allowance','funding','roulette'].forEach(id=>{const btn=$(`.tab[data-tab="${id}"]`);let on=true;if(id==='funding')on=onFunding;if(id==='allowance')on=onAllowance;if(id==='donation'||id==='preset')on=onDonation;if(id==='roulette')on=onRoulette;btn?.classList.toggle('off',!on)})}
function renderForms(){renderCreatorChecks('donationCreatorChecks');renderCreatorChecks('presetCreatorChecks');$('#presetProcess').innerHTML=presetOptions();renderFundingSelect();renderRoulette();renderDisplay();renderState()}
async function mobileBroadcastLogin(){try{const pw=$('#mobileBroadcastPw').value.trim();if(!pw)throw new Error('방송 비밀번호를 입력하세요.');const bid=active?.id||settings?.broadcast?.id;if(!bid)throw new Error('현재 방송 정보를 찾을 수 없습니다.');await api('/api/broadcast-login',{method:'POST',body:JSON.stringify({broadcastId:bid,password:pw})});mobileAuth={broadcastId:bid,password:pw};saveBroadcastPassword(pw);hideLoginGate();showSuccess('로그인 완료')}catch(e){showError('크리에이터 로그인',e)}}
async function saveDisplay(){try{await api('/api/settings',{method:'POST',body:JSON.stringify({overlaySections:settings.overlaySections,...authBody()})});showSuccess('노출 저장 완료');await loadAll(false)}catch(e){handleError('노출',e)}}
async function saveDonation(){try{if(!isLive())throw new Error('방송시작 상태에서만 입력할 수 있습니다.');const donor=norm($('#donor').value);const amount=toWon($('#donationAmount').value);const source=selectedSource('donationSourceChecks');const selected=selectedCreators('donationCreatorChecks');const memo=norm($('#donationMemo').value);if(!donor)throw new Error('도네이터명을 입력하세요.');if(amount<=0)throw new Error('금액을 입력하세요.');if(!selected.length)throw new Error('크리에이터를 선택하세요.');for(const creator of selected){const body={donor,creator,processType:'후원',accountAmount:source==='account'?amount:0,toonieAmount:source==='toonie'?amount:0,memo,...authBody()};await api('/api/donations',{method:'POST',body:JSON.stringify(body)})}['donor','donationAmount','donationMemo'].forEach(clearInput);showSuccess(`후원 저장 완료 ${selected.length}건`);await Promise.all([loadAll(false),loadRecent()])}catch(e){handleError('후원입력',e)}}
async function savePresetManual(){try{if(!isLive())throw new Error('방송시작 상태에서만 수동 입력할 수 있습니다.');const donor=norm($('#presetDonor').value);const count=Math.max(0,parseInt($('#presetCount').value||'0',10)||0);const selected=selectedCreators('presetCreatorChecks');const raw=$('#presetProcess').value||'';const [presetId,presetSide]=(raw.split(':'));const direction=$('#presetDirection').value||'plus';if(!raw)throw new Error('프리셋을 선택하세요.');if(!donor)throw new Error('도네이터명을 입력하세요.');if(count<=0)throw new Error('갯수를 입력하세요.');if(!selected.length)throw new Error('크리에이터를 선택하세요.');for(const creator of selected){const body={kind:'presetCount',donor,creator,presetId,presetSide,direction,count,...authBody()};await api('/api/manual-entry',{method:'POST',body:JSON.stringify(body)})}['presetDonor'].forEach(clearInput);$('#presetCount').value='1';showSuccess(`프리셋 ${direction==='minus'?'제외':'추가'} 완료 ${selected.length}건`);await Promise.all([loadAll(false),loadRecent()])}catch(e){handleError('프리셋 수동입력',e)}}
async function saveAllowance(){try{const body={amount:toWon($('#allowanceAmount').value),direction:$('#allowanceDirection').value,...authBody()};if(body.amount<=0)throw new Error('용돈 금액을 입력하세요.');await api('/api/allowance/adjust',{method:'POST',body:JSON.stringify(body)});clearInput('allowanceAmount');showSuccess('용돈 저장 완료');await loadAll(false)}catch(e){handleError('용돈 수동변경',e)}}
async function saveFundingDirect(){try{const f=currentFunding();if(!f)throw new Error('펀딩을 선택하세요.');const data=JSON.parse(JSON.stringify(settings.fundingData||{items:[]}));const item=(data.items||[]).find(x=>String(x.id)===String(f.id));if(!item)throw new Error('펀딩을 찾을 수 없습니다.');item.current=Math.max(0,toWon($('#fundingCurrent').value));item.target=Math.max(0,toWon($('#fundingTarget').value));await api('/api/funding-data',{method:'POST',body:JSON.stringify({fundingData:data,...authBody()})});showSuccess('펀딩 금액 저장 완료');await loadAll(false)}catch(e){handleError('펀딩금액 변경',e)}}
async function saveFundingManual(){try{if(!isLive())throw new Error('방송시작 상태에서만 수동 입력할 수 있습니다.');const f=currentFunding();if(!f)throw new Error('펀딩을 선택하세요.');const donor=norm($('#fundDonor').value);const amount=toWon($('#fundAmount').value);if(!donor)throw new Error('도네이터명을 입력하세요.');if(amount<=0)throw new Error('금액을 입력하세요.');const body={kind:'funding',fundingId:f.id,donor,amount,sourceType:$('#fundSource').value,memo:'',...authBody()};await api('/api/manual-entry',{method:'POST',body:JSON.stringify(body)});['fundDonor','fundAmount'].forEach(clearInput);showSuccess('펀딩 추가 저장 완료');await Promise.all([loadAll(false),loadRecent()])}catch(e){handleError('펀딩 후원 추가',e)}}
async function startRoulette(){try{const ids=selectedRouletteIds();if(!ids.length)throw new Error('룰렛을 선택하세요.');setRouletteSelected(ids[0]);const body={listId:ids[0],count:$('#rouletteCount').value||1,duration:$('#rouletteDuration').value||undefined,...authBody()};await api('/api/roulette/start',{method:'POST',body:JSON.stringify(body)});showSuccess('룰렛 시작');await loadAll(false)}catch(e){handleError('룰렛 시작',e)}}
async function resetRoulette(){try{await api('/api/roulette/reset',{method:'POST',body:JSON.stringify(authBody())});showSuccess('룰렛 초기화');await loadAll(false)}catch(e){handleError('룰렛 초기화',e)}}
async function advanceRoulette(){try{await api('/api/roulette/advance',{method:'POST',body:JSON.stringify(authBody())});showSuccess('다음 룰렛 실행');await loadAll(false)}catch(e){handleError('룰렛 다음',e)}}
async function loadRecent(){try{const d=await api('/api/donations');const arr=(d.donations||[]).slice(-30).reverse();$('#recentList').innerHTML=arr.length?arr.map((x,i)=>`<div class="recent"><div class="num">${i+1}</div><div><b>${esc(x.donor||'-')} → ${esc(x.creator||'-')}</b><div class="muted">${fmt(x.totalAmount||x.amount||0)}원 · ${esc(x.resultLabel||x.processType||'')}</div></div><button class="btn mini red" style="width:56px" onclick="deleteRecent('${esc(x.id)}')">삭제</button></div>`).join(''):'<div class="empty">최근 입력 없음</div>'}catch(e){$('#recentList').innerHTML=`<div class="muted danger-note">${esc(e.message)}</div>`}}
async function deleteRecent(id){if(!confirm('이 입력을 삭제할까요?'))return;try{await api('/api/donations/'+encodeURIComponent(id),{method:'DELETE',body:JSON.stringify(authBody())});showSuccess('삭제 완료');await Promise.all([loadAll(false),loadRecent()])}catch(e){handleError('최근입력 삭제',e)}}
async function loadStationInfo(){const info=await api('/api/station-info');station=info.station||null;active=info.active||null;return info}
async function loadAll(showToast){await loadStationInfo();settings=await api('/api/settings');settings.station=station;settings.broadcast=active;$('#info').textContent=`${station?.name||STATION} / ${active?.title||'현재 방송'} / ${isLive()?'방송중':'입력잠김'}`;$('#loginInfo').textContent=`${station?.name||STATION} / 현재 방송: ${active?.title||'없음'}`;renderForms();if(showToast)showSuccess('새로고침 완료')}
function switchTab(id){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===id))}
$('#tabs').addEventListener('click',e=>{const b=e.target.closest('.tab');if(b)switchTab(b.dataset.tab)});
function openOverlay(){const token=settings?.station?.overlayToken||station?.overlayToken||'';window.open(`/overlay.html?station=${encodeURIComponent(STATION)}&token=${encodeURIComponent(token)}&monitor=1&v=${Date.now()}`,'_blank')}
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target?.id==='mobileBroadcastPw')mobileBroadcastLogin()});
async function init(){try{await loadAll(false);const saved=getSavedBroadcastPassword();if(active?.id&&saved){try{await api('/api/broadcast-login',{method:'POST',body:JSON.stringify({broadcastId:active.id,password:saved})});mobileAuth={broadcastId:active.id,password:saved};hideLoginGate();await loadRecent();return}catch(e){clearSavedBroadcastPassword()}}showLoginGate();await loadRecent()}catch(e){showError('초기 로딩',e);showLoginGate()}}
init();
