const assert=require('node:assert/strict');const mount=require('../collection-review');
(async()=>{const handlers=new Map(),tables={station_collection_rules:[],broadcast_collection_rules:[]};let names=['빵떠기','국고'],active={id:'broadcast-1'},manager=true,lastRows;
const station={id:'station-1',slug:'duugi'};
const supabase={from(table){const filters=[];return{select(){return this},eq(k,v){filters.push([k,v]);return this},async maybeSingle(){return{data:(tables[table]||[]).find(r=>filters.every(([k,v])=>r[k]===v))||null,error:null}},async upsert(row){let list=tables[table]||(tables[table]=[]),old=list.find(r=>r.station_id===row.station_id&&r.broadcast_id===row.broadcast_id);if(old)Object.assign(old,row);else list.push(row);return{error:null}}}},async rpc(name,args){lastRows=args.p_rows;return{data:{ok:true,donations:args.p_rows},error:null}}};
const app={get(p,h){handlers.set('GET '+p,h)},post(p,h){handlers.set('POST '+p,h)}};
const service=mount(app,{supabase,getStationContext:async()=>({station,active}),managerAllowed:async()=>manager,stationAllowed:async()=>manager,ensureActiveBroadcast:async()=>active,readEffectiveSettings:async()=>({creators:names}),saveEffectiveSettings:async(s,b,v)=>names=v.creators,inputAllowedForActiveBroadcast:async()=>true,makeDonationRow:b=>({donor:b.donor,creator:b.creator,checks:[]}),notify(){},afterApply:async()=>{}});
async function call(method,path,body={}){let value,code=200;const res={status(n){code=n;return this},json(v){value=v;return this}};await handlers.get(method+' '+path)({body},res);return{code,value};}
let result=await call('GET','/api/station/collection-rules');assert.equal(result.value.mode,'collab');assert.equal(result.value.targets.length,2);
const c={mode:'solo',targets:[{id:'stable-a',name:'빵떠기',group:'streamer',aliases:['떠기'],active:true},{id:'stable-b',name:'국고',group:'other',active:true}]};
assert.equal((await call('POST','/api/station/collection-rules',c)).value.ok,true);assert.deepEqual(names,['빵떠기','국고']);assert.equal((await call('GET','/api/station/collection-rules')).value.mode,'solo');
let prepared=await service.prepare('account',{donor:'열려',amount:100},station);assert.equal(prepared.routing.state,'auto');
c.targets[0].name='떠기 새이름';assert.equal((await call('POST','/api/station/collection-rules',c)).value.ok,true);await service.auto({id:'event',source:'account',amount:100,status:'pending',broadcast_id:active.id,routing:prepared.routing},station);assert.equal(lastRows[0].creator,'떠기 새이름');assert.equal(lastRows[0].total_amount,100);
active={id:'broadcast-2'};const next=(await call('GET','/api/station/collection-rules')).value;assert.equal(next.mode,'collab');assert.equal(next.targets[0].id,'stable-a');manager=false;assert.equal((await call('POST','/api/station/collection-rules',c)).code,403);
console.log('PASS integrated rules: legacy list match, per-broadcast mode, stable IDs across rename, exact won and permission');})().catch(e=>{console.error(e);process.exit(1)});
